### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by set-soft** [pages-themes/leap-day#45]
The theme looks really nice thanks!

I have some suggestions and questions. As this is the first time I run jekyll I'm not sure how useful they are ;-)

1. In order to get jekyll working I had to add `gem "kramdown-parser-gfm"` to `Gemfile`. Without it I got messages saying `kramdown-parser-gfm` wasn't installed.

2. The `script/bootstrap` script is designed to mess with the user system, instead of just install things in the user home. IMHO this is a very bad idea.

3. I don't understand why the theme wastes so much user screen for screen sizes over tha 1060px. I also don't understand why so much sizes are hardcoded in pixels. As I said before I know nothing about jekyll, I just wanted to read images from my repo in an easy way when I found I had to use GitHub pages. So them I saw the templates and really liked this one. For my [site](https://inti-cmnb.github.io/kibot_variants_arduprog/) I'm using:

```css
section
{
 width:85%;
 right: -13%;
}
#banner
{
 right:1%;
 margin-right:0px;
 .fork
 {
  left:15%;
  margin-left:0;
 }
}
.wrapper
{
 width:95%
}
nav
{
 width: 14%;
 left:0;
 margin-left:0;
}
footer
{
 width: 14%;
 left:0;
 margin-left:0;
}
```
